apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-demo-app-run
spec:
  pipelineRef:
    name: npm-docker-rt-pipeline
  serviceAccountName: 'default'
  params:
    - name: rturl
      value: https://swampup-swampup.apps.swampup-red-hat.openshiftk8s.com/artifactory
    - name: server
      value: swampup-swampup.apps.swampup-red-hat.openshiftk8s.com
    - name: username
      value: admin
    - name: apikey
      value: AKCp8ii9LdmkGYCGgcoADWNbJuYAfZS4srYwhYd9RwJo1rz3nYWTn9ZvufvHNUrxpZVZ8mDLD
    - name: serverid
      value: openshift-rt-server
    - name: image
      value: "swampup-swampup.apps.swampup-red-hat.openshiftk8s.com/swampup-docker/demo-docker-app"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
